### PR TITLE
Removing generic type hints to support Python version < 3.9

### PR DESCRIPTION
**Pull request by Pankul94**
Removed the generic type hints and tested it on Python 3.8 interpreter.

### CODE REVIEW

**Review by sidsbrmnn — CHANGES_REQUESTED** [review]
Hi @Pankul94,

You're right. Python 3.8 does not support subscripting a type. We can replace `list[bytearray]` with just `list` to retain type defs while not getting an error for older Python versions.

That would be the only change I'd recommend. Otherwise this looks good to me.

Cheers.

**Review by sidsbrmnn — APPROVED** [review]
Thanks @Pankul94. These changes are perfect.

**Comment by Pankul94** [comment]
Thanks for your help, can we please get this merged and released on pypi.

**Review by konidev20 — APPROVED** [review]
LGTM.

**Pull request merged**
